window.SQL_MASTERY_MODULE = {
  "id": "business-kpis",
  "title": "business kpis",
  "learningPath": 9,
  "questionCount": 35,
  "database": "../../databases/business-kpis.sqlite",
  "storageKey": "sqlMasteryBusinessKpisV2",
  "patternGoal": {
    "recognize": [
      "revenue",
      "active customers",
      "conversion",
      "repeat rate",
      "average order value",
      "best-selling",
      "salary growth",
      "span of control"
    ],
    "think": [
      "business definition",
      "numerator",
      "denominator",
      "grain",
      "time period",
      "population",
      "conditional aggregation"
    ]
  },
  "frameworkPrompts": [
    "What business metric is being requested?",
    "What is the exact numerator?",
    "What is the exact denominator?",
    "What population should be included?",
    "What grain should one result row represent?",
    "Should inactive or zero-value entities be included?",
    "Does the KPI require a time period or status filter?",
    "Should the result be a count, amount, average, rate, or percentage?"
  ],
  "questions": [
    {
      "num": 1,
      "difficulty": "Revenue KPIs",
      "text": "Calculate total revenue.",
      "sql": "SELECT ROUND(SUM(quantity * unit_price), 2) AS total_revenue\nFROM order_items;",
      "hints": [
        "Revenue is quantity multiplied by unit_price.",
        "Sum revenue across all order items.",
        "Round the result to two decimal places."
      ],
      "orderSensitive": false,
      "validation": {
        "type": "single-metric",
        "requiredColumns": [
          "total_revenue"
        ],
        "optionalColumns": [],
        "allowExtraColumns": true,
        "ignoreColumnNames": true,
        "numericTolerance": 0.011,
        "orderSensitive": false
      }
    },
    {
      "num": 2,
      "difficulty": "Revenue KPIs",
      "text": "Calculate revenue generated from Completed orders only.",
      "sql": "SELECT ROUND(SUM(oi.quantity * oi.unit_price), 2) AS completed_order_revenue\nFROM orders AS o\nINNER JOIN order_items AS oi ON oi.order_id = o.order_id\nWHERE o.status = 'Completed';",
      "hints": [
        "Join orders to order_items.",
        "Filter for Completed status.",
        "Sum line-item revenue."
      ],
      "orderSensitive": false,
      "validation": {
        "type": "single-metric",
        "requiredColumns": [
          "completed_order_revenue"
        ],
        "optionalColumns": [],
        "allowExtraColumns": true,
        "ignoreColumnNames": true,
        "numericTolerance": 0.011,
        "orderSensitive": false
      }
    },
    {
      "num": 3,
      "difficulty": "Revenue KPIs",
      "text": "Calculate total revenue for each product.",
      "sql": "SELECT\n  p.product_id,\n  p.product_name,\n  ROUND(COALESCE(SUM(oi.quantity * oi.unit_price), 0), 2) AS total_revenue\nFROM products AS p\nLEFT JOIN order_items AS oi ON oi.product_id = p.product_id\nGROUP BY p.product_id, p.product_name;",
      "hints": [
        "Start from products.",
        "Use LEFT JOIN to keep unsold products.",
        "Group by product."
      ],
      "orderSensitive": false,
      "validation": {
        "type": "grouped-metric",
        "requiredColumns": [
          "product_id",
          "total_revenue"
        ],
        "optionalColumns": [
          "product_name"
        ],
        "allowExtraColumns": true,
        "ignoreColumnNames": true,
        "numericTolerance": 0.011,
        "orderSensitive": false
      }
    },
    {
      "num": 4,
      "difficulty": "Revenue KPIs",
      "text": "Calculate total revenue by product category.",
      "sql": "SELECT\n  p.category,\n  ROUND(SUM(oi.quantity * oi.unit_price), 2) AS total_revenue\nFROM products AS p\nINNER JOIN order_items AS oi ON oi.product_id = p.product_id\nGROUP BY p.category;",
      "hints": [
        "Join products to order_items.",
        "Use category as the grouping field.",
        "Sum quantity multiplied by unit_price."
      ],
      "orderSensitive": false,
      "validation": {
        "type": "grouped-metric",
        "requiredColumns": [
          "category",
          "total_revenue"
        ],
        "optionalColumns": [],
        "allowExtraColumns": true,
        "ignoreColumnNames": true,
        "numericTolerance": 0.011,
        "orderSensitive": false
      }
    },
    {
      "num": 5,
      "difficulty": "Revenue KPIs",
      "text": "Calculate total revenue generated by each customer.",
      "sql": "SELECT\n  c.customer_id,\n  c.customer_name,\n  ROUND(COALESCE(SUM(oi.quantity * oi.unit_price), 0), 2) AS total_revenue\nFROM customers AS c\nLEFT JOIN orders AS o ON o.customer_id = c.customer_id\nLEFT JOIN order_items AS oi ON oi.order_id = o.order_id\nGROUP BY c.customer_id, c.customer_name;",
      "hints": [
        "Start from customers.",
        "Join through orders to order_items.",
        "Use LEFT JOIN so inactive customers remain visible."
      ],
      "orderSensitive": false,
      "validation": {
        "type": "grouped-metric",
        "requiredColumns": [
          "customer_id",
          "total_revenue"
        ],
        "optionalColumns": [
          "customer_name"
        ],
        "allowExtraColumns": true,
        "ignoreColumnNames": true,
        "numericTolerance": 0.011,
        "orderSensitive": false
      }
    },
    {
      "num": 6,
      "difficulty": "Revenue KPIs",
      "text": "Calculate total revenue by country.",
      "sql": "SELECT\n  c.country,\n  ROUND(SUM(oi.quantity * oi.unit_price), 2) AS total_revenue\nFROM customers AS c\nINNER JOIN orders AS o ON o.customer_id = c.customer_id\nINNER JOIN order_items AS oi ON oi.order_id = o.order_id\nGROUP BY c.country;",
      "hints": [
        "Country comes from customers.",
        "Revenue comes from order_items.",
        "Group by country."
      ],
      "orderSensitive": false,
      "validation": {
        "type": "grouped-metric",
        "requiredColumns": [
          "country",
          "total_revenue"
        ],
        "optionalColumns": [],
        "allowExtraColumns": true,
        "ignoreColumnNames": true,
        "numericTolerance": 0.011,
        "orderSensitive": false
      }
    },
    {
      "num": 7,
      "difficulty": "Revenue KPIs",
      "text": "Calculate monthly revenue.",
      "sql": "SELECT\n  strftime('%Y-%m', o.order_date) AS revenue_month,\n  ROUND(SUM(oi.quantity * oi.unit_price), 2) AS total_revenue\nFROM orders AS o\nINNER JOIN order_items AS oi ON oi.order_id = o.order_id\nGROUP BY strftime('%Y-%m', o.order_date)\nORDER BY revenue_month;",
      "hints": [
        "Extract year and month from order_date.",
        "Join to order_items.",
        "Order chronologically."
      ],
      "orderSensitive": true,
      "validation": {
        "type": "single-metric",
        "requiredColumns": [
          "revenue_month",
          "total_revenue"
        ],
        "optionalColumns": [],
        "allowExtraColumns": true,
        "ignoreColumnNames": true,
        "numericTolerance": 0.011,
        "orderSensitive": true
      }
    },
    {
      "num": 8,
      "difficulty": "Revenue KPIs",
      "text": "Calculate each product category's percentage contribution to total revenue.",
      "sql": "WITH category_revenue AS (\n  SELECT p.category, SUM(oi.quantity * oi.unit_price) AS total_revenue\n  FROM products AS p\n  INNER JOIN order_items AS oi ON oi.product_id = p.product_id\n  GROUP BY p.category\n),\noverall AS (\n  SELECT SUM(total_revenue) AS grand_total FROM category_revenue\n)\nSELECT\n  c.category,\n  ROUND(c.total_revenue, 2) AS total_revenue,\n  ROUND(100.0 * c.total_revenue / NULLIF(o.grand_total, 0), 2) AS revenue_percentage\nFROM category_revenue AS c\nCROSS JOIN overall AS o;",
      "hints": [
        "Calculate revenue by category first.",
        "Calculate overall revenue separately.",
        "Divide each category total by the grand total."
      ],
      "orderSensitive": false,
      "validation": {
        "type": "percentage-rate",
        "requiredColumns": [
          "category",
          "total_revenue",
          "revenue_percentage"
        ],
        "optionalColumns": [],
        "allowExtraColumns": true,
        "ignoreColumnNames": true,
        "numericTolerance": 0.011,
        "orderSensitive": false
      }
    },
    {
      "num": 9,
      "difficulty": "Customer KPIs",
      "text": "Calculate the number of active customers.",
      "sql": "SELECT COUNT(DISTINCT customer_id) AS active_customers\nFROM orders;",
      "hints": [
        "Active means having at least one order.",
        "Count distinct customer_id values in orders.",
        "No join is required."
      ],
      "orderSensitive": false,
      "validation": {
        "type": "single-metric",
        "requiredColumns": [
          "active_customers"
        ],
        "optionalColumns": [],
        "allowExtraColumns": true,
        "ignoreColumnNames": true,
        "numericTolerance": 0.011,
        "orderSensitive": false
      }
    },
    {
      "num": 10,
      "difficulty": "Customer KPIs",
      "text": "Calculate the number of customers who have never placed an order.",
      "sql": "SELECT COUNT(*) AS inactive_customers\nFROM customers AS c\nWHERE NOT EXISTS (\n  SELECT 1 FROM orders AS o WHERE o.customer_id = c.customer_id\n);",
      "hints": [
        "Start from customers.",
        "Use NOT EXISTS against orders.",
        "Count the remaining customers."
      ],
      "orderSensitive": false,
      "validation": {
        "type": "single-metric",
        "requiredColumns": [
          "inactive_customers"
        ],
        "optionalColumns": [],
        "allowExtraColumns": true,
        "ignoreColumnNames": true,
        "numericTolerance": 0.011,
        "orderSensitive": false
      }
    },
    {
      "num": 11,
      "difficulty": "Customer KPIs",
      "text": "Calculate the percentage of customers who have placed at least one order.",
      "sql": "SELECT ROUND(\n  100.0 * COUNT(DISTINCT o.customer_id) / NULLIF(COUNT(DISTINCT c.customer_id), 0),\n  2\n) AS active_customer_percentage\nFROM customers AS c\nLEFT JOIN orders AS o ON o.customer_id = c.customer_id;",
      "hints": [
        "The numerator is active customers.",
        "The denominator is all customers.",
        "Use decimal division and NULLIF."
      ],
      "orderSensitive": false,
      "validation": {
        "type": "percentage-rate",
        "requiredColumns": [
          "active_customer_percentage"
        ],
        "optionalColumns": [],
        "allowExtraColumns": true,
        "ignoreColumnNames": true,
        "numericTolerance": 0.011,
        "orderSensitive": false
      }
    },
    {
      "num": 12,
      "difficulty": "Customer KPIs",
      "text": "Calculate the average revenue generated per customer.",
      "sql": "WITH customer_revenue AS (\n  SELECT\n    c.customer_id,\n    COALESCE(SUM(oi.quantity * oi.unit_price), 0) AS total_revenue\n  FROM customers AS c\n  LEFT JOIN orders AS o ON o.customer_id = c.customer_id\n  LEFT JOIN order_items AS oi ON oi.order_id = o.order_id\n  GROUP BY c.customer_id\n)\nSELECT ROUND(AVG(total_revenue), 2) AS average_revenue_per_customer\nFROM customer_revenue;",
      "hints": [
        "Calculate one revenue total per customer.",
        "Include customers with zero revenue.",
        "Average those customer totals."
      ],
      "orderSensitive": false,
      "validation": {
        "type": "grouped-metric",
        "requiredColumns": [
          "average_revenue_per_customer"
        ],
        "optionalColumns": [],
        "allowExtraColumns": true,
        "ignoreColumnNames": true,
        "numericTolerance": 0.011,
        "orderSensitive": false
      }
    },
    {
      "num": 13,
      "difficulty": "Customer KPIs",
      "text": "Calculate the repeat customer rate.",
      "sql": "WITH customer_orders AS (\n  SELECT customer_id, COUNT(*) AS order_count\n  FROM orders\n  GROUP BY customer_id\n)\nSELECT ROUND(\n  100.0 * SUM(CASE WHEN order_count > 1 THEN 1 ELSE 0 END)\n  / NULLIF(COUNT(*), 0),\n  2\n) AS repeat_customer_rate\nFROM customer_orders;",
      "hints": [
        "First count orders per active customer.",
        "Repeat customers have more than one order.",
        "Divide repeat customers by active customers."
      ],
      "orderSensitive": false,
      "validation": {
        "type": "percentage-rate",
        "requiredColumns": [
          "repeat_customer_rate"
        ],
        "optionalColumns": [],
        "allowExtraColumns": true,
        "ignoreColumnNames": true,
        "numericTolerance": 0.011,
        "orderSensitive": false
      }
    },
    {
      "num": 14,
      "difficulty": "Customer KPIs",
      "text": "Calculate the average number of days between customer signup and first order.",
      "sql": "WITH first_orders AS (\n  SELECT customer_id, MIN(order_date) AS first_order_date\n  FROM orders\n  GROUP BY customer_id\n)\nSELECT ROUND(\n  AVG(julianday(f.first_order_date) - julianday(c.signup_date)),\n  2\n) AS average_days_to_first_order\nFROM customers AS c\nINNER JOIN first_orders AS f ON f.customer_id = c.customer_id\nWHERE date(f.first_order_date) >= date(c.signup_date);",
      "hints": [
        "Find each customer's first order date.",
        "Measure the date difference with julianday().",
        "Average valid non-negative intervals."
      ],
      "orderSensitive": false,
      "validation": {
        "type": "single-metric",
        "requiredColumns": [
          "average_days_to_first_order"
        ],
        "optionalColumns": [],
        "allowExtraColumns": true,
        "ignoreColumnNames": true,
        "numericTolerance": 0.011,
        "orderSensitive": false
      }
    },
    {
      "num": 15,
      "difficulty": "Customer KPIs",
      "text": "Identify high-value customers based on total revenue of at least 1000.",
      "sql": "SELECT\n  c.customer_id,\n  c.customer_name,\n  ROUND(SUM(oi.quantity * oi.unit_price), 2) AS total_revenue\nFROM customers AS c\nINNER JOIN orders AS o ON o.customer_id = c.customer_id\nINNER JOIN order_items AS oi ON oi.order_id = o.order_id\nGROUP BY c.customer_id, c.customer_name\nHAVING SUM(oi.quantity * oi.unit_price) >= 1000;",
      "hints": [
        "Aggregate revenue by customer.",
        "Use HAVING after grouping.",
        "Apply the 1000 threshold."
      ],
      "orderSensitive": false,
      "validation": {
        "type": "identify-entity",
        "requiredColumns": [
          "customer_id"
        ],
        "optionalColumns": [
          "customer_name"
        ],
        "allowExtraColumns": true,
        "ignoreColumnNames": true,
        "numericTolerance": 0.011,
        "orderSensitive": false
      }
    },
    {
      "num": 16,
      "difficulty": "Order KPIs",
      "text": "Calculate the total number of orders.",
      "sql": "SELECT COUNT(*) AS total_orders\nFROM orders;",
      "hints": [
        "Use COUNT(*) on orders.",
        "No joins are needed.",
        "Return one value."
      ],
      "orderSensitive": false,
      "validation": {
        "type": "single-metric",
        "requiredColumns": [
          "total_orders"
        ],
        "optionalColumns": [],
        "allowExtraColumns": true,
        "ignoreColumnNames": true,
        "numericTolerance": 0.011,
        "orderSensitive": false
      }
    },
    {
      "num": 17,
      "difficulty": "Order KPIs",
      "text": "Calculate the Completed order rate.",
      "sql": "SELECT ROUND(\n  100.0 * SUM(CASE WHEN status = 'Completed' THEN 1 ELSE 0 END) / COUNT(*),\n  2\n) AS completed_order_rate\nFROM orders;",
      "hints": [
        "Count Completed orders conditionally.",
        "Divide by total orders.",
        "Multiply by 100.0."
      ],
      "orderSensitive": false,
      "validation": {
        "type": "percentage-rate",
        "requiredColumns": [
          "completed_order_rate"
        ],
        "optionalColumns": [],
        "allowExtraColumns": true,
        "ignoreColumnNames": true,
        "numericTolerance": 0.011,
        "orderSensitive": false
      }
    },
    {
      "num": 18,
      "difficulty": "Order KPIs",
      "text": "Calculate the Cancelled order rate.",
      "sql": "SELECT ROUND(\n  100.0 * SUM(CASE WHEN status = 'Cancelled' THEN 1 ELSE 0 END) / COUNT(*),\n  2\n) AS cancelled_order_rate\nFROM orders;",
      "hints": [
        "Use conditional aggregation.",
        "Cancelled orders form the numerator.",
        "Divide by all orders."
      ],
      "orderSensitive": false,
      "validation": {
        "type": "percentage-rate",
        "requiredColumns": [
          "cancelled_order_rate"
        ],
        "optionalColumns": [],
        "allowExtraColumns": true,
        "ignoreColumnNames": true,
        "numericTolerance": 0.011,
        "orderSensitive": false
      }
    },
    {
      "num": 19,
      "difficulty": "Order KPIs",
      "text": "Calculate the average order value.",
      "sql": "WITH order_values AS (\n  SELECT order_id, SUM(quantity * unit_price) AS order_value\n  FROM order_items\n  GROUP BY order_id\n)\nSELECT ROUND(AVG(order_value), 2) AS average_order_value\nFROM order_values;",
      "hints": [
        "First calculate one total per order.",
        "Do not average line-item values directly.",
        "Average the order totals."
      ],
      "orderSensitive": false,
      "validation": {
        "type": "single-metric",
        "requiredColumns": [
          "average_order_value"
        ],
        "optionalColumns": [],
        "allowExtraColumns": true,
        "ignoreColumnNames": true,
        "numericTolerance": 0.011,
        "orderSensitive": false
      }
    },
    {
      "num": 20,
      "difficulty": "Order KPIs",
      "text": "Calculate the average number of items per order.",
      "sql": "WITH order_items_count AS (\n  SELECT order_id, SUM(quantity) AS item_count\n  FROM order_items\n  GROUP BY order_id\n)\nSELECT ROUND(AVG(item_count), 2) AS average_items_per_order\nFROM order_items_count;",
      "hints": [
        "Define items as the sum of quantity.",
        "Calculate one total per order.",
        "Average those totals."
      ],
      "orderSensitive": false,
      "validation": {
        "type": "grouped-metric",
        "requiredColumns": [
          "average_items_per_order"
        ],
        "optionalColumns": [],
        "allowExtraColumns": true,
        "ignoreColumnNames": true,
        "numericTolerance": 0.011,
        "orderSensitive": false
      }
    },
    {
      "num": 21,
      "difficulty": "Order KPIs",
      "text": "Identify orders with values above the average order value.",
      "sql": "WITH order_values AS (\n  SELECT order_id, SUM(quantity * unit_price) AS order_value\n  FROM order_items\n  GROUP BY order_id\n),\naverage_value AS (\n  SELECT AVG(order_value) AS average_order_value FROM order_values\n)\nSELECT\n  o.order_id,\n  ROUND(o.order_value, 2) AS order_value\nFROM order_values AS o\nCROSS JOIN average_value AS a\nWHERE o.order_value > a.average_order_value;",
      "hints": [
        "Calculate order values first.",
        "Calculate their average in a second step.",
        "Filter orders above the average."
      ],
      "orderSensitive": false,
      "validation": {
        "type": "identify-entity",
        "requiredColumns": [
          "order_id"
        ],
        "optionalColumns": [],
        "allowExtraColumns": true,
        "ignoreColumnNames": true,
        "numericTolerance": 0.011,
        "orderSensitive": false
      }
    },
    {
      "num": 22,
      "difficulty": "Order KPIs",
      "text": "Identify customers whose average order value is above the overall average order value.",
      "sql": "WITH order_values AS (\n  SELECT\n    o.order_id,\n    o.customer_id,\n    SUM(oi.quantity * oi.unit_price) AS order_value\n  FROM orders AS o\n  INNER JOIN order_items AS oi ON oi.order_id = o.order_id\n  GROUP BY o.order_id, o.customer_id\n),\ncustomer_averages AS (\n  SELECT customer_id, AVG(order_value) AS customer_average_order_value\n  FROM order_values\n  GROUP BY customer_id\n),\noverall_average AS (\n  SELECT AVG(order_value) AS overall_average_order_value\n  FROM order_values\n)\nSELECT\n  c.customer_id,\n  c.customer_name,\n  ROUND(ca.customer_average_order_value, 2) AS customer_average_order_value,\n  ROUND(oa.overall_average_order_value, 2) AS overall_average_order_value\nFROM customer_averages AS ca\nINNER JOIN customers AS c ON c.customer_id = ca.customer_id\nCROSS JOIN overall_average AS oa\nWHERE ca.customer_average_order_value > oa.overall_average_order_value;",
      "hints": [
        "Calculate one value per order first.",
        "Average order values by customer.",
        "Compare each customer average with the overall average."
      ],
      "orderSensitive": false,
      "validation": {
        "type": "identify-entity",
        "requiredColumns": [
          "customer_id"
        ],
        "optionalColumns": [
          "customer_name"
        ],
        "allowExtraColumns": true,
        "ignoreColumnNames": true,
        "numericTolerance": 0.011,
        "orderSensitive": false
      }
    },
    {
      "num": 23,
      "difficulty": "Product KPIs",
      "text": "Identify the best-selling products by quantity sold.",
      "sql": "WITH product_sales AS (\n  SELECT\n    p.product_id,\n    p.product_name,\n    SUM(oi.quantity) AS total_quantity_sold\n  FROM products AS p\n  INNER JOIN order_items AS oi ON oi.product_id = p.product_id\n  GROUP BY p.product_id, p.product_name\n),\nranked AS (\n  SELECT *, RANK() OVER (ORDER BY total_quantity_sold DESC) AS sales_rank\n  FROM product_sales\n)\nSELECT product_id, product_name, total_quantity_sold\nFROM ranked\nWHERE sales_rank = 1;",
      "hints": [
        "Aggregate quantity by product.",
        "Rank totals descending.",
        "Keep rank 1 to preserve ties."
      ],
      "orderSensitive": false,
      "validation": {
        "type": "identify-entity",
        "requiredColumns": [
          "product_id"
        ],
        "optionalColumns": [
          "product_name"
        ],
        "allowExtraColumns": true,
        "ignoreColumnNames": true,
        "numericTolerance": 0.011,
        "orderSensitive": false
      }
    },
    {
      "num": 24,
      "difficulty": "Product KPIs",
      "text": "Identify the best-selling products by total revenue.",
      "sql": "WITH product_revenue AS (\n  SELECT\n    p.product_id,\n    p.product_name,\n    SUM(oi.quantity * oi.unit_price) AS total_revenue\n  FROM products AS p\n  INNER JOIN order_items AS oi ON oi.product_id = p.product_id\n  GROUP BY p.product_id, p.product_name\n),\nranked AS (\n  SELECT *, RANK() OVER (ORDER BY total_revenue DESC) AS revenue_rank\n  FROM product_revenue\n)\nSELECT product_id, product_name, ROUND(total_revenue, 2) AS total_revenue\nFROM ranked\nWHERE revenue_rank = 1;",
      "hints": [
        "Aggregate revenue by product.",
        "Rank totals descending.",
        "Keep the top rank."
      ],
      "orderSensitive": false,
      "validation": {
        "type": "identify-entity",
        "requiredColumns": [
          "product_id"
        ],
        "optionalColumns": [
          "product_name"
        ],
        "allowExtraColumns": true,
        "ignoreColumnNames": true,
        "numericTolerance": 0.011,
        "orderSensitive": false
      }
    },
    {
      "num": 25,
      "difficulty": "Product KPIs",
      "text": "Identify products that have never been sold.",
      "sql": "SELECT\n  p.product_id,\n  p.product_name,\n  p.category,\n  p.price\nFROM products AS p\nWHERE NOT EXISTS (\n  SELECT 1 FROM order_items AS oi WHERE oi.product_id = p.product_id\n);",
      "hints": [
        "Start from products.",
        "Use NOT EXISTS against order_items.",
        "Return products without a match."
      ],
      "orderSensitive": false,
      "validation": {
        "type": "identify-entity",
        "requiredColumns": [
          "product_id"
        ],
        "optionalColumns": [
          "product_name",
          "category"
        ],
        "allowExtraColumns": true,
        "ignoreColumnNames": true,
        "numericTolerance": 0.011,
        "orderSensitive": false
      }
    },
    {
      "num": 26,
      "difficulty": "Product KPIs",
      "text": "Identify products generating below-average revenue.",
      "sql": "WITH product_revenue AS (\n  SELECT\n    p.product_id,\n    p.product_name,\n    COALESCE(SUM(oi.quantity * oi.unit_price), 0) AS total_revenue\n  FROM products AS p\n  LEFT JOIN order_items AS oi ON oi.product_id = p.product_id\n  GROUP BY p.product_id, p.product_name\n),\naverage_revenue AS (\n  SELECT AVG(total_revenue) AS average_product_revenue FROM product_revenue\n)\nSELECT\n  p.product_id,\n  p.product_name,\n  ROUND(p.total_revenue, 2) AS total_revenue\nFROM product_revenue AS p\nCROSS JOIN average_revenue AS a\nWHERE p.total_revenue < a.average_product_revenue;",
      "hints": [
        "Calculate one revenue total per product.",
        "Include zero-revenue products.",
        "Compare each total with the average product revenue."
      ],
      "orderSensitive": false,
      "validation": {
        "type": "identify-entity",
        "requiredColumns": [
          "product_id"
        ],
        "optionalColumns": [
          "product_name"
        ],
        "allowExtraColumns": true,
        "ignoreColumnNames": true,
        "numericTolerance": 0.011,
        "orderSensitive": false
      }
    },
    {
      "num": 27,
      "difficulty": "Product KPIs",
      "text": "Calculate each product category's percentage share of total revenue.",
      "sql": "WITH category_revenue AS (\n  SELECT p.category, SUM(oi.quantity * oi.unit_price) AS total_revenue\n  FROM products AS p\n  INNER JOIN order_items AS oi ON oi.product_id = p.product_id\n  GROUP BY p.category\n),\noverall AS (\n  SELECT SUM(total_revenue) AS grand_total FROM category_revenue\n)\nSELECT\n  c.category,\n  ROUND(c.total_revenue, 2) AS total_revenue,\n  ROUND(100.0 * c.total_revenue / NULLIF(o.grand_total, 0), 2) AS revenue_share\nFROM category_revenue AS c\nCROSS JOIN overall AS o;",
      "hints": [
        "Aggregate revenue by category.",
        "Calculate the grand total.",
        "Divide category revenue by total revenue."
      ],
      "orderSensitive": false,
      "validation": {
        "type": "percentage-rate",
        "requiredColumns": [
          "category",
          "total_revenue",
          "revenue_share"
        ],
        "optionalColumns": [],
        "allowExtraColumns": true,
        "ignoreColumnNames": true,
        "numericTolerance": 0.011,
        "orderSensitive": false
      }
    },
    {
      "num": 28,
      "difficulty": "Product KPIs",
      "text": "Calculate each product's percentage contribution to total revenue.",
      "sql": "WITH product_revenue AS (\n  SELECT\n    p.product_id,\n    p.product_name,\n    COALESCE(SUM(oi.quantity * oi.unit_price), 0) AS total_revenue\n  FROM products AS p\n  LEFT JOIN order_items AS oi ON oi.product_id = p.product_id\n  GROUP BY p.product_id, p.product_name\n),\noverall AS (\n  SELECT SUM(total_revenue) AS grand_total FROM product_revenue\n)\nSELECT\n  p.product_id,\n  p.product_name,\n  ROUND(p.total_revenue, 2) AS total_revenue,\n  ROUND(100.0 * p.total_revenue / NULLIF(o.grand_total, 0), 2) AS revenue_percentage\nFROM product_revenue AS p\nCROSS JOIN overall AS o;",
      "hints": [
        "Calculate revenue by product.",
        "Calculate total revenue separately.",
        "Divide each product total by the grand total."
      ],
      "orderSensitive": false,
      "validation": {
        "type": "percentage-rate",
        "requiredColumns": [
          "product_id",
          "total_revenue",
          "revenue_percentage"
        ],
        "optionalColumns": [
          "product_name"
        ],
        "allowExtraColumns": true,
        "ignoreColumnNames": true,
        "numericTolerance": 0.011,
        "orderSensitive": false
      }
    },
    {
      "num": 29,
      "difficulty": "HR KPIs",
      "text": "Calculate the number of employees in each department.",
      "sql": "SELECT\n  d.department_id,\n  d.department_name,\n  COUNT(e.employee_id) AS employee_count\nFROM departments AS d\nLEFT JOIN employees AS e ON e.department_id = d.department_id\nGROUP BY d.department_id, d.department_name;",
      "hints": [
        "Start from departments.",
        "LEFT JOIN employees.",
        "Count employee_id within each department."
      ],
      "orderSensitive": false,
      "validation": {
        "type": "grouped-metric",
        "requiredColumns": [
          "department_id",
          "employee_count"
        ],
        "optionalColumns": [
          "department_name"
        ],
        "allowExtraColumns": true,
        "ignoreColumnNames": true,
        "numericTolerance": 0.011,
        "orderSensitive": false
      }
    },
    {
      "num": 30,
      "difficulty": "HR KPIs",
      "text": "Calculate the average latest salary for each department.",
      "sql": "WITH latest_salaries AS (\n  SELECT\n    employee_id,\n    salary,\n    ROW_NUMBER() OVER (\n      PARTITION BY employee_id\n      ORDER BY effective_date DESC, salary_id DESC\n    ) AS latest_rank\n  FROM salaries\n)\nSELECT\n  d.department_id,\n  d.department_name,\n  ROUND(AVG(ls.salary), 2) AS average_salary\nFROM departments AS d\nINNER JOIN employees AS e ON e.department_id = d.department_id\nINNER JOIN latest_salaries AS ls\n  ON ls.employee_id = e.employee_id\n AND ls.latest_rank = 1\nGROUP BY d.department_id, d.department_name;",
      "hints": [
        "Use one latest salary per employee.",
        "Join employees to departments.",
        "Average salaries by department."
      ],
      "orderSensitive": false,
      "validation": {
        "type": "grouped-metric",
        "requiredColumns": [
          "department_id",
          "average_salary"
        ],
        "optionalColumns": [
          "department_name"
        ],
        "allowExtraColumns": true,
        "ignoreColumnNames": true,
        "numericTolerance": 0.011,
        "orderSensitive": false
      }
    },
    {
      "num": 31,
      "difficulty": "HR KPIs",
      "text": "Calculate salary growth for each employee from their first salary to their latest salary.",
      "sql": "WITH ranked_salaries AS (\n  SELECT\n    employee_id,\n    salary,\n    ROW_NUMBER() OVER (\n      PARTITION BY employee_id\n      ORDER BY effective_date, salary_id\n    ) AS first_rank,\n    ROW_NUMBER() OVER (\n      PARTITION BY employee_id\n      ORDER BY effective_date DESC, salary_id DESC\n    ) AS latest_rank\n  FROM salaries\n),\nsalary_summary AS (\n  SELECT\n    employee_id,\n    MAX(CASE WHEN first_rank = 1 THEN salary END) AS first_salary,\n    MAX(CASE WHEN latest_rank = 1 THEN salary END) AS latest_salary\n  FROM ranked_salaries\n  GROUP BY employee_id\n)\nSELECT\n  e.employee_id,\n  e.employee_name,\n  s.first_salary,\n  s.latest_salary,\n  ROUND(s.latest_salary - s.first_salary, 2) AS salary_growth_amount,\n  ROUND(100.0 * (s.latest_salary - s.first_salary) / NULLIF(s.first_salary, 0), 2) AS salary_growth_percentage\nFROM salary_summary AS s\nINNER JOIN employees AS e ON e.employee_id = s.employee_id;",
      "hints": [
        "Rank salary records from both directions.",
        "Extract first and latest salary per employee.",
        "Calculate amount and percentage growth."
      ],
      "orderSensitive": false,
      "validation": {
        "type": "grouped-metric",
        "requiredColumns": [
          "employee_id",
          "first_salary",
          "latest_salary",
          "salary_growth_amount",
          "salary_growth_percentage"
        ],
        "optionalColumns": [
          "employee_name"
        ],
        "allowExtraColumns": true,
        "ignoreColumnNames": true,
        "numericTolerance": 0.011,
        "orderSensitive": false
      }
    },
    {
      "num": 32,
      "difficulty": "HR KPIs",
      "text": "Identify the department with the highest average latest salary.",
      "sql": "WITH latest_salaries AS (\n  SELECT employee_id, salary,\n    ROW_NUMBER() OVER (\n      PARTITION BY employee_id\n      ORDER BY effective_date DESC, salary_id DESC\n    ) AS latest_rank\n  FROM salaries\n),\ndepartment_averages AS (\n  SELECT\n    d.department_id,\n    d.department_name,\n    AVG(ls.salary) AS average_salary\n  FROM departments AS d\n  INNER JOIN employees AS e ON e.department_id = d.department_id\n  INNER JOIN latest_salaries AS ls\n    ON ls.employee_id = e.employee_id\n   AND ls.latest_rank = 1\n  GROUP BY d.department_id, d.department_name\n),\nranked AS (\n  SELECT *, RANK() OVER (ORDER BY average_salary DESC) AS salary_rank\n  FROM department_averages\n)\nSELECT department_id, department_name, ROUND(average_salary, 2) AS average_salary\nFROM ranked\nWHERE salary_rank = 1;",
      "hints": [
        "Calculate latest salary per employee.",
        "Average those salaries by department.",
        "Rank department averages and keep the top rank."
      ],
      "orderSensitive": false,
      "validation": {
        "type": "identify-entity",
        "requiredColumns": [
          "department_id"
        ],
        "optionalColumns": [
          "department_name"
        ],
        "allowExtraColumns": true,
        "ignoreColumnNames": true,
        "numericTolerance": 0.011,
        "orderSensitive": false
      }
    },
    {
      "num": 33,
      "difficulty": "HR KPIs",
      "text": "Calculate employee tenure in completed years as of 2026-07-28.",
      "sql": "SELECT\n  employee_id,\n  employee_name,\n  hire_date,\n  CAST(\n    strftime('%Y', '2026-07-28') - strftime('%Y', hire_date)\n    - (strftime('%m-%d', '2026-07-28') < strftime('%m-%d', hire_date))\n    AS INTEGER\n  ) AS tenure_years\nFROM employees;",
      "hints": [
        "Use a fixed reference date for stable results.",
        "Start with the difference in years.",
        "Adjust when the anniversary has not occurred."
      ],
      "orderSensitive": false,
      "validation": {
        "type": "single-metric",
        "requiredColumns": [
          "employee_id",
          "hire_date",
          "tenure_years"
        ],
        "optionalColumns": [
          "employee_name"
        ],
        "allowExtraColumns": true,
        "ignoreColumnNames": true,
        "numericTolerance": 0.011,
        "orderSensitive": false
      }
    },
    {
      "num": 34,
      "difficulty": "HR KPIs",
      "text": "Calculate each manager's span of control.",
      "sql": "SELECT\n  m.employee_id AS manager_id,\n  m.employee_name AS manager_name,\n  COUNT(e.employee_id) AS direct_report_count\nFROM employees AS m\nINNER JOIN employees AS e ON e.manager_id = m.employee_id\nGROUP BY m.employee_id, m.employee_name;",
      "hints": [
        "Join employees to themselves.",
        "Match employee.manager_id to manager.employee_id.",
        "Count direct reports per manager."
      ],
      "orderSensitive": false,
      "validation": {
        "type": "grouped-metric",
        "requiredColumns": [
          "manager_id",
          "direct_report_count"
        ],
        "optionalColumns": [
          "manager_name"
        ],
        "allowExtraColumns": true,
        "ignoreColumnNames": true,
        "numericTolerance": 0.011,
        "orderSensitive": false
      }
    },
    {
      "num": 35,
      "difficulty": "HR KPIs",
      "text": "Identify employees whose latest salary is above their department's average latest salary.",
      "sql": "WITH latest_salaries AS (\n  SELECT\n    employee_id,\n    salary,\n    ROW_NUMBER() OVER (\n      PARTITION BY employee_id\n      ORDER BY effective_date DESC, salary_id DESC\n    ) AS latest_rank\n  FROM salaries\n),\nsalary_analysis AS (\n  SELECT\n    e.employee_id,\n    e.employee_name,\n    d.department_name,\n    ls.salary,\n    AVG(ls.salary) OVER (\n      PARTITION BY e.department_id\n    ) AS department_average_salary\n  FROM employees AS e\n  INNER JOIN departments AS d ON d.department_id = e.department_id\n  INNER JOIN latest_salaries AS ls\n    ON ls.employee_id = e.employee_id\n   AND ls.latest_rank = 1\n)\nSELECT\n  employee_id,\n  employee_name,\n  department_name,\n  salary,\n  ROUND(department_average_salary, 2) AS department_average_salary\nFROM salary_analysis\nWHERE salary > department_average_salary;",
      "hints": [
        "Isolate latest salary rows.",
        "Calculate the department average as a window function.",
        "Filter in an outer query."
      ],
      "orderSensitive": false,
      "validation": {
        "type": "identify-entity",
        "requiredColumns": [
          "employee_id"
        ],
        "optionalColumns": [
          "employee_name",
          "department_name"
        ],
        "allowExtraColumns": true,
        "ignoreColumnNames": true,
        "numericTolerance": 0.011,
        "orderSensitive": false
      }
    }
  ]
};
